"""High-performance Model Context Protocol (MCP) server for FinTech market telemetry."""

from high_performance_model.protocol.server import MCPServer
from high_performance_model.server.app import create_fintech_mcp_server
from high_performance_model.telemetry.benchmark import run_telemetry_benchmark
from high_performance_model.telemetry.buffer import (
    BarAggregator,
    MarketDataBuffer,
    aggregate_bars_from_ticks,
)
from high_performance_model.types import (
    AssetClass,
    Bar,
    BarTimeframe,
    BenchmarkRunResult,
    IndicatorConfig,
    IndicatorType,
    LiquidityTier,
    MarketDepthSnapshot,
    MarketState,
    MarketTelemetrySummary,
    MarketTick,
    OrderBook,
    OrderBookLevel,
    OrderType,
    Quote,
    RiskMetrics,
    Side,
    TechnicalIndicatorResult,
    TimeInForce,
    TradeExecution,
    compute_microprice,
    compute_spread_bps,
    timeframe_to_seconds,
    validate_symbol,
)

__version__ = "0.1.0"
__all__ = [
    "AssetClass",
    "Bar",
    "BarAggregator",
    "BarTimeframe",
    "BenchmarkRunResult",
    "IndicatorConfig",
    "IndicatorType",
    "LiquidityTier",
    "MCPServer",
    "MarketDataBuffer",
    "MarketDepthSnapshot",
    "MarketState",
    "MarketTelemetrySummary",
    "MarketTick",
    "OrderBook",
    "OrderBookLevel",
    "OrderType",
    "Quote",
    "RiskMetrics",
    "Side",
    "TechnicalIndicatorResult",
    "TimeInForce",
    "TradeExecution",
    "aggregate_bars_from_ticks",
    "compute_microprice",
    "compute_spread_bps",
    "create_fintech_mcp_server",
    "run_telemetry_benchmark",
    "timeframe_to_seconds",
    "validate_symbol",
]
