"""High-performance Model Context Protocol (MCP) server for FinTech market telemetry."""

from high_performance_model.alerts import (
    AlertEngine,
    AlertEvent,
    AlertRule,
    AlertType,
)
from high_performance_model.execution import (
    ExecutionSimulator,
    OrderStatus,
    Portfolio,
    Position,
    SimulatedOrder,
)
from high_performance_model.protocol.server import MCPServer
from high_performance_model.protocol.transports import (
    MemoryTransport,
    SSEServer,
    SSETransport,
    StdioTransport,
)
from high_performance_model.risk import (
    MonteCarloConfig,
    MonteCarloStressResult,
    MonteCarloStressTester,
    RiskLevel,
    RiskRatioResult,
    RiskTelemetrySnapshot,
    StressScenario,
    StressTestResult,
    StressTestingSuite,
    calculate_calmar_ratio,
    calculate_downside_deviation,
    calculate_omega_ratio,
    calculate_sharpe_ratio,
    calculate_sortino_ratio,
    compute_comprehensive_risk_ratios,
)
from high_performance_model.server.app import create_fintech_mcp_server
from high_performance_model.storage import (
    HistoricalReplayEngine,
    MarketDataPersistence,
    load_buffer_snapshot,
    save_buffer_snapshot,
)
from high_performance_model.telemetry.benchmark import run_telemetry_benchmark
from high_performance_model.telemetry.buffer import (
    BarAggregator,
    MarketDataBuffer,
    aggregate_bars_from_ticks,
)
from high_performance_model.types import (
    AssetClass,
    Bar,
    BarTimeframe,
    BenchmarkRunResult,
    IndicatorConfig,
    IndicatorType,
    LiquidityTier,
    MarketDepthSnapshot,
    MarketState,
    MarketTelemetrySummary,
    MarketTick,
    OrderBook,
    OrderBookLevel,
    OrderType,
    Quote,
    RiskMetrics,
    Side,
    Symbol,
    TechnicalIndicatorResult,
    TimeInForce,
    TradeExecution,
    compute_microprice,
    compute_spread_bps,
    timeframe_to_seconds,
    validate_symbol,
)

__version__ = "0.1.0"
__all__ = [
    "AlertEngine",
    "AlertEvent",
    "AlertRule",
    "AlertType",
    "AssetClass",
    "Bar",
    "BarAggregator",
    "BarTimeframe",
    "BenchmarkRunResult",
    "ExecutionSimulator",
    "HistoricalReplayEngine",
    "IndicatorConfig",
    "IndicatorType",
    "LiquidityTier",
    "MCPServer",
    "MarketDataBuffer",
    "MarketDataPersistence",
    "MarketDepthSnapshot",
    "MarketState",
    "MarketTelemetrySummary",
    "MarketTick",
    "MemoryTransport",
    "MonteCarloConfig",
    "MonteCarloStressResult",
    "MonteCarloStressTester",
    "OrderBook",
    "OrderBookLevel",
    "OrderStatus",
    "OrderType",
    "Portfolio",
    "Position",
    "Quote",
    "RiskLevel",
    "RiskMetrics",
    "RiskRatioResult",
    "RiskTelemetrySnapshot",
    "SSEServer",
    "SSETransport",
    "Side",
    "SimulatedOrder",
    "StdioTransport",
    "StressScenario",
    "StressTestResult",
    "StressTestingSuite",
    "Symbol",
    "TechnicalIndicatorResult",
    "TimeInForce",
    "TradeExecution",
    "aggregate_bars_from_ticks",
    "calculate_calmar_ratio",
    "calculate_downside_deviation",
    "calculate_omega_ratio",
    "calculate_sharpe_ratio",
    "calculate_sortino_ratio",
    "compute_comprehensive_risk_ratios",
    "compute_microprice",
    "compute_spread_bps",
    "create_fintech_mcp_server",
    "load_buffer_snapshot",
    "run_telemetry_benchmark",
    "save_buffer_snapshot",
    "timeframe_to_seconds",
    "validate_symbol",
]
